export const metadata = {
  title: 'Outra página',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1>Outro Header</h1>
      {children}
    </>
  );
}
